### ISSUE TITLE
[ISSUE] Crashes with 1.21.2 & 1.21.3

### ISSUE THREAD

**Issue by XDPXI** [XDPXI/XDLib#36]
**Describe the bug**
```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'xdlib' at 'dev.xdpxi.xdlib.XDsLibrary'!
at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
at knot//net.minecraft.class_310.<init>(class_310.java:482)
at knot//net.minecraft.client.main.Main.main(Main.java:248)
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NullPointerException: Item id not set
at java.base/java.util.Objects.requireNonNull(Unknown Source)
at knot//net.minecraft.class_1792$class_1793.method_63689(class_1792.java:251)
at knot//net.minecraft.class_1792.<init>(class_1792.java:114)
at knot//dev.xdpxi.xdlib.api.custom.Item(custom.java:50)
at knot//dev.xdpxi.xdlib.api.custom.Item(custom.java:61)
at knot//dev.xdpxi.xdlib.XDsLibrary.registerItems(XDsLibrary.java:146)
at knot//dev.xdpxi.xdlib.XDsLibrary.onInitialize(XDsLibrary.java:184)
at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
... 6 more
```

**To Reproduce**
- Run 1.21.2 or above

**Expected behavior**
Crash.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Minecraft Version: 1.21.2 & 1.21.3
 - Loader Version: Fabric
 - Java Version: 21
 - Mod Version: [56ba926](https://github.com/XDPXI/XDLib/commit/56ba)

**Comment by XDPXI** [comment]
I am currently working to fix the issue, it may take a while because I have no idea why `Item item = new Item(new Item.Settings());` and `return Item(itemID, modID, null);` doesn't work.

**Comment by XDPXI** [comment]
Custom API has been migrated!

**Comment by XDPXI** [comment]
Support for 1.21.2 and 1.21.3 has been accomplished!
